-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 20:58:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca2024
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca2024
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca2024` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca2024` ;

-- -----------------------------------------------------
-- Table `biblioteca2024`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca2024`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `fone` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca2024`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca2024`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca2024`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca2024`.`autores` (
  `idautores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idautores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca2024`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca2024`.`livros` (
  `idlivros` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  `autores_idautores` INT NOT NULL,
  PRIMARY KEY (`idlivros`),
  INDEX `fk_livros_categorias1_idx` (`categorias_idcategorias` ASC),
  INDEX `fk_livros_autores1_idx` (`autores_idautores` ASC),
  CONSTRAINT `fk_livros_categorias1`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `biblioteca2024`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livros_autores1`
    FOREIGN KEY (`autores_idautores`)
    REFERENCES `biblioteca2024`.`autores` (`idautores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca2024`.`emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca2024`.`emprestimos` (
  `idemprestimos` INT NOT NULL AUTO_INCREMENT,
  `usuarios_idusuarios` INT NOT NULL,
  `livros_idlivros` INT NOT NULL,
  `dtemprestimo` DATE NOT NULL,
  `dtentrega` DATE NULL,
  INDEX `fk_usuarios_has_livros_livros1_idx` (`livros_idlivros` ASC),
  INDEX `fk_usuarios_has_livros_usuarios_idx` (`usuarios_idusuarios` ASC),
  PRIMARY KEY (`idemprestimos`),
  CONSTRAINT `fk_usuarios_has_livros_usuarios`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `biblioteca2024`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_livros_livros1`
    FOREIGN KEY (`livros_idlivros`)
    REFERENCES `biblioteca2024`.`livros` (`idlivros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
