-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 04:09:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ead03-oficina-Rogerio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ead03-oficina-Rogerio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ead03-oficina-Rogerio` DEFAULT CHARACTER SET utf8 ;
USE `ead03-oficina-Rogerio` ;

-- -----------------------------------------------------
-- Table `ead03-oficina-Rogerio`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ead03-oficina-Rogerio`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ead03-oficina-Rogerio`.`mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ead03-oficina-Rogerio`.`mecanicos` (
  `idmecanicos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idmecanicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ead03-oficina-Rogerio`.`carros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ead03-oficina-Rogerio`.`carros` (
  `idcarros` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `placa` VARCHAR(7) NOT NULL,
  `clientes_idclientes` INT NOT NULL,
  PRIMARY KEY (`idcarros`),
  INDEX `fk_carros_clientes_idx` (`clientes_idclientes` ASC),
  CONSTRAINT `fk_carros_clientes`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `ead03-oficina-Rogerio`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ead03-oficina-Rogerio`.`ordem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ead03-oficina-Rogerio`.`ordem` (
  `idordem` INT NOT NULL AUTO_INCREMENT,
  `carros_idcarros` INT NOT NULL,
  `mecanicos_idmecanicos` INT NOT NULL,
  `defeito` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NOT NULL DEFAULT 0,
  INDEX `fk_carros_has_mecanicos_mecanicos1_idx` (`mecanicos_idmecanicos` ASC),
  INDEX `fk_carros_has_mecanicos_carros1_idx` (`carros_idcarros` ASC),
  PRIMARY KEY (`idordem`),
  CONSTRAINT `fk_carros_has_mecanicos_carros1`
    FOREIGN KEY (`carros_idcarros`)
    REFERENCES `ead03-oficina-Rogerio`.`carros` (`idcarros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carros_has_mecanicos_mecanicos1`
    FOREIGN KEY (`mecanicos_idmecanicos`)
    REFERENCES `ead03-oficina-Rogerio`.`mecanicos` (`idmecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
